server:
  port: 8084

spring:
  application:
    name: shopsy-ai-service
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-dummy-key-replace-in-prod}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
